name: Roll-out

on:
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  terraform-apply:
    environment: helloworld
    name: Terraform Apply
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.13.1
    
    - name: Terraform Init
      run: terraform init
      working-directory: terraform
    
    # - name: Terraform Apply
    #   run: terraform apply -auto-approve
    #   working-directory: terraform

    - name: Store SSH private key in GitHub Secret
      working-directory: terraform
      env:
        SECRET_MANAGER_TOKEN: ${{ secrets.SECRET_MANAGER_TOKEN }}
      run: |
        SSH_KEY=$(terraform output -raw ssh_private_key)
        echo "$SSH_KEY" | gh secret set SSH_PRIVATE_KEY \
          --env helloworld \
          --repo ${{ github.repository }}
